### ISSUE TITLE
Error: plugin compiled to start DFS (Hadoop 2.7.0)

### ISSUE THREAD

**Issue by rmunjuluri** [winghc/hadoop2x-eclipse-plugin#24]
I tried starting the DFS in Eclipse using a plugin that I built following the instructions. When I try to connect the DFS node, i get the following error

!ENTRY org.eclipse.core.jobs 4 2 2015-07-04 15:45:42.286
!MESSAGE An internal error occurred during: "Map/Reduce location status updater".
!STACK 0
java.lang.NullPointerException
        at org.apache.hadoop.mapred.JobClient.getAllJobs(JobClient.java:814)
        at org.apache.hadoop.mapred.JobClient.jobsToComplete(JobClient.java:790)
        at org.apache.hadoop.eclipse.server.HadoopServer$LocationStatusUpdater.run(HadoopServer.java:119)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by wukonggg** [comment]
i find same problem on hadoop-2.7.1

ant compile pluginin success, but run failed
