### ISSUE TITLE
eclipse indigo, hadoop 2.4.0 nullpointer  "Map/Reduce location status updater". 

### ISSUE THREAD

**Issue by eskuai** [winghc/hadoop2x-eclipse-plugin#26]
Hello,

I compiled hadoop2.4.0-eclipse-plugin, but, running into my indigo eclipse, always get:

!ENTRY org.eclipse.core.jobs 4 2 2015-08-06 18:01:04.954
!MESSAGE An internal error occurred during: "Map/Reduce location status updater".
!STACK 0
java.lang.NullPointerException
        at oC(JobClient.java:814)
        at org.apache.hadoop.mapred.JobClient.jobsToComplete(JobClient.java:790)
        at org.apache.hadoop.eclipse.server.HadoopServer$LocationStatusUpdater.run(HadoopServer.j
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by sisyphus177** [comment]
Same issue with self-compiled hadoop 2.7.2 and eclipse Neon.

**Comment by zhouna** [comment]
I encountered the same problem with hadoop 2.8.3 and eclipse Mars. I solved the problem according this blog: http://blog.csdn.net/l1028386804/article/details/52665022. 

hadoop fs -mkdir /Administrator

change 'Administrator' to your username.
