### ISSUE TITLE
Hadoop2.7.1: An internal error occurred during: "Connecting to DFS MyHadoop". org/apache/htrace/SamplerBuilder

### ISSUE THREAD

**Issue by emailfeifan** [winghc/hadoop2x-eclipse-plugin#30]
ant compile plugin success, but run failed.
any one know how to solve it?

**Comment by chenyuanchen** [comment]
I got the same error.  do you have the  solution 。

**Comment by wangzhics** [comment]
i have the same problem
i already build success by change the "libraries.properties" file, when i use the build artifact in eclipse, it occurred error: "An internal error occurred during: "Connecting to DFS localhost"."
`java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hdfs.DFSConfigKeys
    at org.apache.hadoop.hdfs.DFSClient$Conf.<init>(DFSClient.java:509)
    at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:638)
    at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
    at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
    at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653)
    at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
    at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
    at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:170)
    at org.apache.hadoop.eclipse.server.HadoopServer.getDFS(HadoopServer.java:478)
    at org.apache.hadoop.eclipse.dfs.DFSPath.getDFS(DFSPath.java:146)
    at org.apache.hadoop.eclipse.dfs.DFSFolder.loadDFSFolderChildren(DFSFolder.java:61)
    at org.apache.hadoop.eclipse.dfs.DFSFolder$1.run(DFSFolder.java:178)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

**Comment by wangzhics** [comment]
just use the release artifact, the hadoop-eclipse-plugin-2.6.0.jar work for me!

**Comment by husty866** [comment]
@wangzhics , thanks,  hadoop-eclipse-plugin-2.6.0.jar  works for me with hadoop 2.7.2
