### ISSUE TITLE
Stuck at New hadoop Location (Hadoop v2.8.0)

### ISSUE THREAD

**Issue by Abouhassane** [winghc/hadoop2x-eclipse-plugin#39]
When i try to create new hadoop location and i try to scroll down the location i get this error:

**An internal error occurred during: "Map/Reduce location status updater". java.lang.NullPointerException**

The log of eclipse outputs the Following:

```
!ENTRY org.eclipse.ui 4 0 2017-04-24 15:09:44.921
>!MESSAGE Unhandled event loop exception
!STACK 0
> java.lang.NullPointerException
at org.apache.hadoop.eclipse.servers.HadoopLocationWizard$TabAdvanced.notifyChange(HadoopLocationWizard.java:949)
at org.apache.hadoop.eclipse.servers.HadoopLocationWizard$TabMediator.fireChange(HadoopLocationWizard.java:481)
at org.apache.hadoop.eclipse.servers.HadoopLocationWizard$TabMediator.notifyChange(HadoopLocationWizard.java:324)
at org.apache.hadoop.eclipse.servers.HadoopLocationWizard$TabMediator$2.run(HadoopLocationWizard.java:385)
at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
at org.eclipse.swt.widgets.Display.syncExec(Display.java:4491)
at org.apache.hadoop.eclipse.servers.HadoopLocationWizard$TabMediator.notifyChange(HadoopLocationWizard.java:354)
at org.apache.hadoop.eclipse.servers.HadoopLocationWizard$TabMain$1.run(HadoopLocationWizard.java:865)
at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
at org.eclipse.swt.widgets.Display.syncExec(Display.java:4491)
at org.apache.hadoop.eclipse.servers.HadoopLocationWizard$TabMain.modifyText(HadoopLocationWizard.java:863)
at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:179)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1392)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3742)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3363)
at org.eclipse.jface.window.Window.runEventLoop(Window.java:826)
at org.eclipse.jface.window.Window.open(Window.java:802)
at org.apache.hadoop.eclipse.actions.NewLocationAction.run(NewLocationAction.java:60)
at org.eclipse.jface.action.Action.runWithEvent(Action.java:499)
at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1392)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3742)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3363)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

!ENTRY org.eclipse.core.jobs 4 2 2017-04-24 15:09:53.277
>!MESSAGE An internal error occurred during: "Map/Reduce location status updater".
!STACK 0
>java.lang.NullPointerException
at org.apache.hadoop.mapred.JobClient.getAllJobs(JobClient.java:851)
at org.apache.hadoop.mapred.JobClient.jobsToComplete(JobClient.java:827)
at org.apache.hadoop.eclipse.server.HadoopServer$LocationStatusUpdater.run(HadoopServer.java:119)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

**Comment by Abouhassane** [comment]
Well the source of the problem was the 2 fold:
1- Bad Configuration in hadoop/etc/hadoop/core-site.xml & hdfs-site.xml & mapred-site.xml; the correct configuration is the following:

    **core-site.xml:**
<configuration>
	<property>
		<name>fs.defaultFS</name>
		<value>hdfs://localhost:9000</value>
	</property>
	<property>
		<name>hadoop.tmp.dir</name>
		<value>/home/hadoop/hdfs/tmp</value>
		<description>A base for other temporary directories.</description>
	</property>
</configuration>

   **hdfs-site.xml:**

<configuration>
	<property>
		<name>dfs.replication</name>
		<value>1</value>
	</property>
	<property>
    		<name>dfs.data.dir</name>
		<value>/home/hadoop/hdfs/data</value>
	</property>
	<property>
		<name>dfs.name.dir</name>
		<value>/home/hadoop/hdfs/name</value>
	</property>
</configuration>

   **mapred-site.xml:**

<configuration>
	<property>
		<name>mapreduce.framework.name</name>
		<value>yarn</value>
	</property>
	<property>
		<name>mapred.job.tracker</name>
		<value>localhost:9001</value>
	</property>
</configuration>

2- the hdfs base was emtpy so i needed to fill it, for me i created 2 folder /input /output and i put a file in input

**Comment by zhouna** [comment]
I got the same problem with hadoop 2.8.3 and eclipse Mars. I solved the problem according to this blog: http://blog.csdn.net/l1028386804/article/details/52665022.

hadoop fs -mkdir /Administrator

change 'Administrator' to your username.

**Comment by junsionzhang** [comment]
@zhouna do you test the  oxygen version?

**Comment by zhouna** [comment]
@junsionzhang I'm sorry to see it now.
Yes, tested. You can download it from here: http://download.csdn.net/download/familyshizhouna/10172755

**Comment by junsionzhang** [comment]
@zhouna  can you tell me how to  compile it  ,the steps ?
