### ISSUE TITLE
Can not create a Hadoop Eclipse server...

### ISSUE THREAD

**Issue by olcaysah** [winghc/hadoop2x-eclipse-plugin#7]
Hello,
I successfully created a hadoop plugin jar file and copied into the eclipse plugin folder. When I try to create a dfs server I have following error. I tried with different guava releases but I still have same error.

Could you please help me. 

Thank you.

java.lang.NoClassDefFoundError: com/google/common/collect/Interners
    at org.apache.hadoop.util.StringInterner.<clinit>(StringInterner.java:48)
    at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2108)
    at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2001)
    at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:1918)
    at org.apache.hadoop.conf.Configuration.get(Configuration.java:721)
    at org.apache.hadoop.eclipse.server.HadoopServer.addPluginConfigDefaultProperties(HadoopServer.java:450)
    at org.apache.hadoop.eclipse.server.HadoopServer.<init>(HadoopServer.java:229)
    at org.apache.hadoop.eclipse.servers.HadoopLocationWizard.<init>(HadoopLocationWizard.java:88)
    at org.apache.hadoop.eclipse.actions.NewLocationAction$1.<init>(NewLocationAction.java:41)
    at org.apache.hadoop.eclipse.actions.NewLocationAction.run(NewLocationAction.java:40)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:499)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:588)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:505)
    at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:456)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4421)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3771)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3391)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1122)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1006)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:146)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:611)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:565)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:125)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:109)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:80)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:372)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:226)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Interners cannot be found by osgi.identity; osgi.identity="org.apache.hadoop.eclipse"; type="osgi.bundle"; version:Version="0.18.0"; singleton:="true"
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:411)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:331)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:323)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    ... 40 more

**Comment by Coook** [comment]
you can down guava-r09.jar。
